### ISSUE TITLE
Allow user remove their profile.

### ISSUE THREAD

**Issue by jonathancross** [grmmph/couchfugee#2]
After adding their profile to the site, users have no way to remove themselves later.
1. First step would be to post an email address, Google form or other means to have themselves removed.
2. If time allows, we could work on some way for users to remove themselves automatically (tricky without creating accounts, but maybe the "crawler" can help here).

**Comment by grmmph** [comment]
Well, why not just let them remove the same way they've added themselves?
`People.remove(id)`

**Comment by jonathancross** [comment]
Yeah, we could just let them remove that way, but anyone could just remove anyone else.  Even accidentally.

One option would be to have user add a special note to their CS profile (eg `couchfugee=remove`) and then force a refresh (as discussed on #3) on the couchfugee site.

Probably other options we can think of.  Maybe a CS api exists?

**Comment by grmmph** [comment]
People can also add other people without authentication.

I wouldn't make it so complicated. At the end this is a referral site and not a real platform. Registering, adding notes on profile ect seems like a huge overkill for me.

**Comment by jonathancross** [comment]
Yeah, simple is good.
I was just thinking that we could simplify all of this by creating a [CS group](https://www.couchsurfing.com/groups/new), then just have people join or unjoin to "signup".

This would also give us a way to make announcements, have users share experiences, etc.
