### ISSUE TITLE
Refresh user's profile information from CS

### ISSUE THREAD

**Issue by jonathancross** [grmmph/couchfugee#3]
Currently, the site creates a snapshot of CS information when a new profile is added.
Changes on CS are not reflected in the site.

**Example:**
I for example had my profile set to "Maybe Accepting Guests".  It is now permanently set to that value on the site: http://couchfugee.grmmph.com/results/Aeugst%20am%20Albis

Obviously we want to limit the number of times CS is crawled.

**Temporary solution**
A quick hack might be re-crawling CS when handling [`personAlreadyExist`](/grmmph/couchfugee/blob/master/csrw/client/add.js#L15) condition.  We could present user with an "Refresh my profile information" button as an example.

**Comment by grmmph** [comment]
I'm just thinking this "Accepting Guest" status is not relevant to show to users.
Maybe instead we can show number of references instead. That's more relevant information in my opinion.

For updating this information, I would suggest we'll set a timer in the server to re-crawl the number of references every month at Sunday midnight.

Any thoughts?

**Comment by jonathancross** [comment]
Automatically recrawling sounds great, but a manual options seems important as well for those who do not wish to leave CS profile public.

Explanation:
I almost didn't signup because I did not want to have all of my CS profile info open to the public.
The option to make public, register, then make private again (only visible to those registered on CS) was important for me.  In the auto-crawl scenario, I would have to leave CS profile public until the next crawl.
